server:
  address: 0.0.0.0
  port: 8080

spring:
  mvc.view.suffix: .html
  mustache.servlet.cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c6yezxqldllc.ap-northeast-2.rds.amazonaws.com:3306/rustDB?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&autoReconnection=ture
    username: admin
    password: shrtmfdjTwh

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false